[workspace]
members = [
    "crates/tfheprus-core",
    "crates/tfheprus-circuits",
    "crates/tfheprus-prover",
    "crates/tfheprus-cli",
]
exclude = ["thirdparties/Plonky3-recursion"]
resolver = "2"

[workspace.package]
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/virtualsecureplatform/TFHEprus"

[workspace.dependencies]
rand = "0.8"
rand_chacha = "0.3"
thiserror = "1"
p3-batch-stark = { git = "https://github.com/Plonky3/Plonky3", rev = "56952503e1401a62982ceaf952c5e4a829b61803" }
p3-circuit = { path = "thirdparties/Plonky3-recursion/circuit" }
p3-circuit-prover = { path = "thirdparties/Plonky3-recursion/circuit-prover" }
p3-field = { git = "https://github.com/Plonky3/Plonky3", rev = "56952503e1401a62982ceaf952c5e4a829b61803" }
p3-goldilocks = { git = "https://github.com/Plonky3/Plonky3", rev = "56952503e1401a62982ceaf952c5e4a829b61803" }
